### ISSUE TITLE
For Avro data Store domain objects as bytes in internal avro structures

### ISSUE THREAD

**Issue by andybryant** [simplesourcing/simplesource#21]
At IAG Thomas used a cunning technique in a general many-to-many join function where custom keys and values are just stored as bytes in the internal Avro data structures. This removes the need to generate custom wrapper structures on the fly, but still supports schema evolution of the underlying data. The trick is to use the Confluent serdes to serialize/deserialize the bytes when needed and pass in a fake topic to use for storing the schemas in the schema registry.

**Comment by andybryant** [comment]
You can then use Avro IDL to define all the internal schemas and use generated specific types in the Avro serialization codebase removing the need for all the nasty complex custom schema code.

**Comment by szoio** [comment]
Sounds like a better way of doing things, but just to make sure I'm understanding correctly:
* We create avdl for the message types, e.g. `ComandRequest` and use `bytes` in the AVDL for anything that is generic.
* Create Java object for these avdl definitions.
* Create mappers to map between e.g. `CommandRequest` <==> `AvroCommandRequest`.
* Separately serialise the generic domain objects. If these are `SpeciificRecord`s generated from domain specific avdl, we get the serdes for these for free.
* Plug the serialised bytes into the message objects.

**Comment by andybryant** [comment]
That all sounds correct. Will see if we can get the manyToMany join function we developed here to be open sourced to show how we did it here.

**Comment by andybryant** [comment]
Had a change of heart on this. It's clunky to provide a good schema registry subject to use when serializing the events/commands since we don't have access to the app-id to append. It's also handy having these objects visible when viewing the data via the avro console consumer. Let's leave as is.
